### ISSUE TITLE
3.3.1 breaks add-ons which use additional columns in message list pane

### ISSUE THREAD

**Issue by stanleyaccrington** [Ericsson/exchangecalendar#112]
Installing exchangecalendar 3.3.1 (any rc version) breaks at least two of my other add-ons, namely Show InOut [from http://www.ggbs.de/extensions/ShowInOut.html] which adds two extra columns to the message list pane, and XNote++ [http://www.froihofer.net/xnote/] which can add one. When exchangecalendar is enabled, these additional columns disappear from the message list pane, and no longer appear in the list of selectable columns, making these add-ons unusable. Disabling exchangecalendar restrores correct behaviour of both add-ons.

System = TB 31.4.0 (identified as 'up to date') + Lightning 3.3.3 on Win 7

**Comment by muthusuba** [comment]
It might have something to do with the new columns that were introduced...

**Comment by saper17** [comment]
Same problem here.  Show InOut stopped working after installing exchange calendar 3.3.1-rc4.  Disabling exchange calendar restored proper functioning of Show InOut.  I have been using Show InOut for   I note that the release note versions 0.7.9 and 1.0.0 of Show InOut (back in 2010, 2011) mention that they fixed incompatibilities with other extensions using custom columns.   Does exchangecalendar have a custom column?  If so perhaps it would be useful to see how Show InOut implemented them.

System: Thunderbird 31.5.0, Lightning 3.3.3, exchangecalendar 3.3.1~rc4, Show InOut 1.1.0.  On Scientific Linux 6.6 and on Mac OS X 10.10.2

**Comment by bavincen** [comment]
https://github.com/Ericsson/exchangecalendar/commit/a4c1848a2fd7ce8e672fb91e8eef5ca92c32e5ff

Thanks @anantks

**Comment by muthusuba** [comment]
@bavincen If I understood the patch right - there was some problem with 'Invite Column' ?

**Comment by bavincen** [comment]
@muthusuba  it was breaking other addon *xnote" so we fixed it :)
now its totally fine..

**Comment by bavincen** [comment]
Btw problem was with priority col.. I

-----Original Message-----

**Comment by saper17** [comment]
Still broken.  I have installed exchangecalendar 3.3.1~rc5 and it still breaks Show InOut 1.1.2.  (Using Thunderbird 31.5.0 and Lightning 3.3.3 on Scientific Linux 6.6.)  Show InOut offers two very useful new columns, Correspondent and In/Out.  When exchangecalendar 3.3.1~rc5 is installed, these two columns disappear; when exchangecalendar is disabled, the two columns reappear.

**Comment by bavincen** [comment]
Please use our latest code...
Please refer our wiki page for further information 

-----Original Message-----

**Comment by saper17** [comment]
I apologize; I thought I had been.  Indeed, using commit https://github.com/Ericsson/exchangecalendar/commit/a4c1848a2fd7ce8e672fb91e8eef5ca92c32e5ff does not break Show InOut.

**Comment by bavincen** [comment]
Thanks for confirming
