### ISSUE TITLE
Invite column feature troubles during new mail account creation

### ISSUE THREAD

**Issue by asg1290** [Ericsson/exchangecalendar#119]
I have been testing 3.3.1-rc4 and noticed my thunderbird locking up.  I fired up the jsconcole and see a ton of these messages.

************************************************************
* Call to xpconnect wrapped JSObject produced this error:  *
[Exception... "[JavaScript Error: "too much recursion"]"  nsresult: "0x80570021 (NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS)"  location: "JS frame :: chrome://exchangecalendar/content/invite-style.js :: getMessageBody :: line 162"  data: yes]
************************************************************

**Comment by asg1290** [comment]
FWIW i deleted and re-added the calendar and it seems to be happier now.  This makes rolling out the newer plugin a little bit of a pain.

**Comment by bavincen** [comment]
Hi
We are fixing this..

Thanks

**Comment by asg1290** [comment]
I updated my plugin and noticed the hanging.  I did recreate my mailbox at one point trying to fix the issue.  Only deleting and recreating the calendar got me unstuck.

**Comment by mwtalbert** [comment]
This is affecting me as well. Any information I can provide?

**Comment by pkdevel** [comment]
hey guys, i have the same issue.

i created a completely new profile, without adding any calendars i still get this exception

**Comment by bavincen** [comment]
please use our latest code.. 

https://github.com/Ericsson/exchangecalendar/wiki/How-to-Install-latest-addon
