### ISSUE TITLE
NS_ERROR_XPC_NEED_OUT_OBJECT

### ISSUE THREAD

**Issue by tfft** [Ericsson/exchangecalendar#242]
I'm getting the following error in the error console anytime I move the mouse over a message.

Timestamp: 2015-06-18 7:12:36 PM
Error: NS_ERROR_XPC_NEED_OUT_OBJECT: 'Out' argument must be an object arg 1 [nsIMsgCustomColumnHandler.getRowProperties]
Source File: chrome://exchangecalendar/content/priority-display.js
Line: 178

**Comment by bavincen** [comment]
are you enabled priority column? if yes do you see icons for higher n lower priority instead of text

**Comment by tfft** [comment]
No I don't have priority column enabled.  These are my enabled column items in this order,
 - Thread
 - Calendar Invite
 - Attachments
 - Starred
 - Read
 - Date
 - From
 - Size

Let me know if you need more info.

**Comment by tfft** [comment]
I disabled each of the columns separately yet the errors continued to show-up.  Let me know if you'd like to me to try something to pin down what the problem is.

**Comment by bavincen** [comment]
@tfft  I am unable to reproduce

**Comment by tfft** [comment]
What information would you like me to share or is there anything you'd like me to do (debug) to narrow down this issue ?  My error console is full of these errors - I get one or two of these messages anytime the mouse goes over one of the listed email messages.  I'm using "Unicode" character encoding (in case that matters) and this happens in all folders - inbox, sent, trash, etc.

Timestamp: 2015-06-22 1:28:28 PM
Error: NS_ERROR_XPC_NEED_OUT_OBJECT: 'Out' argument must be an object arg 1 [nsIMsgCustomColumnHandler.getRowProperties]
Source File: chrome://exchangecalendar/content/priority-display.js
Line: 178

Would looking at the "Out" argument in context give any clues within the code ?

**Comment by tfft** [comment]
In passing, I was looking at the following [Mozilla Developer Network - MDN] (https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsITreeView) page to get an idea about "getRowProperties" and noticed that it notes it as **Obsolete since Gecko 22** - is this relevant ?

**Comment by bavincen** [comment]
Thanks @tfft  That could be the reason. Are you using latest TB or seamonky..

**Comment by tfft** [comment]
Latest TB (38.0.1) with your fine beta-3.

**Comment by tfft** [comment]
The error is still there with beta-4.

**Comment by bavincen** [comment]
yes, we need a fix @tfft :)
'
 
https://github.com/Ericsson/exchangecalendar/blob/4a82ce7b2c5c41a1d36e86f463018400b91df966/chrome/content/priority-display.js

**Comment by bavincen** [comment]
closing it.. i guess we already fixed this long back.

**Comment by tfft** [comment]
I'm still getting these errors with the latest code (3.5.0) - where/how has it been fixed ?

**Comment by chrislong** [comment]
I'm also getting this with 3.5.0. (Linux, Thunderbird 38.6.0, Lightning 4.0.5.2)

**Comment by mdima** [comment]
Maybe there is some sort of interaction with this addon: I stopped to get the error when I disabled this component.
https://addons.mozilla.org/it/thunderbird/addon/enhanced-priority-display/
