### ISSUE TITLE
Addon activates global search & indexer

### ISSUE THREAD

**Issue by dwomble** [Ericsson/exchangecalendar#370]
I finally tracked down my inability to turn off Tbird's global search indexer to this addon. Verified that this addon is the cause by starting a new profile and testing just with this addon enabled and disabled. When disabled I can turn off the global search indexer when the addon is enabled the search indexer automatically becomes re-activated after a restart.

**Comment by bavincen** [comment]
We use it for Email Followup feature? what do you recommend

**Comment by dwomble** [comment]
Two thoughts. 

1. Be clear that the addon will forcibly activate indexing
or
2. Let people turn off indexing but tell them they will lose the follow up functionality so they can choose. 

I disable indexing because it causing large delays due to disk I/O and rely on google for my searching. 

Derek

**Comment by NeoRaider** [comment]
I think exchangecalendar should touch this setting under no circumstances; if the user has disabled global indexing, there is probably reason for it. Showing a warning in the addon's settings that "Task Followup" won't work without global indexing is enough in my opinion.

This issue makes exchangecalendar completely unusable for me, as I have subscribed some very high-volume mailing lists, and global indexing makes thunderbird use 100% CPU all the time when you have a few 100k mails...

**Comment by bavincen** [comment]
@NeoRaider yeah global indexing will be set disabled, when the follow up is not needed

**Comment by bavincen** [comment]
https://github.com/Ericsson/exchangecalendar/commit/7eac848db075e21ab8f68ef8ffd894f824d1b752

**Comment by bavincen** [comment]
fixed

**Comment by cvoltz** [comment]
I have version 3.5.0 of the extension and I verified that the changes in the patch were present in exchangeSettings.dtd but I still see the problem. If exchangecalendar is enabled, global indexing is enabled. Only disabling the add-on allows me to turn global indexing off and retain the setting.

**Comment by zmanion** [comment]
Confirm this behavior with 3.8.0-beta2.

**Comment by architetto-colombo70** [comment]
I confirm that this problem is also present with version 3.8.0-beta3.

**Comment by StefanKaerst** [comment]
Hi,
because of #580 I use EWS 4.0.1002 and can confirm that global indexer remains on.
settings in exchangeSettings.dtd's are present ("Disable Followup Task")
my thunderbird profile is > 5.5G and my notebook uses a SSD, so I want to switch off the indexer.
